### PR TITLE
[BUG]: Fixed navbar and darkmode issue

### LINKED ISSUE #538: Navbar & Dark Mode Issue
Hello @cleveranu , @Shreyaar12 
Here is a bug regarding the Navbar and the darkmode.
- Please assignm me this so I can fix the issue.

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
## Description
Hello @cleveranu ,
I have fixed the navbar and the darkmode issue bug which is the major bug for the website because website is not showing the navbar.So I have fixed the issue and it's now wokring properly you can review it and it is super ready to merge. 👍🏻 

## Fixed Issue Video 
[Screencast from 04-08-23 10:25:26 PM IST.webm](https://github.com/ssitvit/Code-Canvas/assets/121503426/2a892ca2-255f-4562-9c15-f524a1e5bbce)

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
@cleveranu can you please review this.

**Review by Shreyaar12 — CHANGES_REQUESTED** [review]
Kindly rectify the excess white space in the light mode at the end of the page after the footer. Also in the light mode the pictures are getting a negative colour in the cards (pretty obvious in the one for top 10 rated netflix films). Kindly fix these both.

**Comment by Shreyaar12** [comment]
@SyedImtiyaz-1 Hi, first of all not adding  a navbar was the essence of the design of this page and not an "issue" per say. 
Kindly fix the issues mentioned in review.

**Comment by SyedImtiyaz-1** [comment]
@Shreyaar12 Okay.

**Comment by SyedImtiyaz-1** [comment]
@Shreyaar12 Please add hosted link in the about section it is easier for the contributor for quick checks
image

**Pull request merged**
