### PR TITLE
Greeting Bot added

### PR DESCRIPTION
**Pull request by apoorvaron**
@Dharmesh177 To run this workflow you need to enable the following permission
settings>Actions>General>workflow Permissions

Screenshot 2023-06-04 at 10 50 17 AM

### CODE REVIEW

**Comment by apoorvaron** [comment]
@Dharmesh177 Review this

**Comment by Dharmesh177** [comment]
Request review from @Shreyaar12

**Comment by Shreyaar12** [comment]
These permissions were already enabled.. Keep up the good work!

**Comment by apoorvaron** [comment]
@Shreyaar12 Please add label 2

**Pull request merged**
