### PR TITLE
[GSSoC'23] Dots-Boxes Game Completed

### LINKED ISSUE #384: [GSSoC'23] Dots and Boxes Game
- Front end project
- Tech using HTML, CSS and JS
- Multi player game
- With best sound quality
- Adding attractive and smooth user interface and best experience to the user

We have played this game so many times in our childhood. It's rules are so simple,
More the boxes you have got, more will your score and you will be the winner of this game.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Related Issue - 384

Closes #384 

## Description
- This game is single player game.
- Adding AI functionality.
- More the closed boxes a player created, more will be your score.

## Screenshots
image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @artimanputra @cleveranu 
Please review this pr and requested to merge for a successful contribution under GSSoC'23 program.

Sir, i want to tell you that i have also send a dots and boxes game in gamezone but this game functionality and look is totally different from that game. This game has a functionality of AI so that pc can also play with you that's why this game is a single player game.

But that game is a multi-player game.

I also requested to you sir, please add label of `level 3` on this game.
Thanks for assigning this project to me.

**Comment by Dharmesh177** [comment]
Resolve conflict

**Comment by Avdhesh-Varshney** [comment]
> Resolve conflict

@Dharmesh177 Conflicts resolved

**Comment by Dharmesh177** [comment]
Add rule and steps to play game and explain how it's working

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 Sir, please again review this pr.
Rules added !

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @artimanputra @cleveranu please review this pr
i have created this pr last week. Please again review this pr

**Comment by cleveranu** [comment]
good work

**Pull request merged**
