### PR TITLE
Added Music Player to the repository.

### LINKED ISSUE #10: Music Player

### PR DESCRIPTION
**Pull request by Nishannaik**
This is my first ever contribution to open source were i have contributing to simple  music player code to this website later I have to attach page there to here.

## Related Issue

Closes #10 

## Description

Hii I have designed a simple basic music player with help of html, css, javascript which play song and we can change unlimited songs we want later in code we can change bg, songs and design whatever you want !! thanks @cleveranu for your guidance. Please check my code any help and suggestions are appreciated it is great to work with your project and exciting part !!

## Screenshots

Screen shot added below [link of screenshot as mentioned here](https://drive.google.com/drive/folders/1Pk6E9DKxApxb04jSba73VxUqnYkaxccY?usp=sharing)
## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Nishannaik** [comment]
I have designed a basic music player for Gsoc 23. closed #10

**Comment by Dharmesh177** [comment]
Not able to find your project in home page
follow contributing.md file

**Comment by Shreyaar12** [comment]
Refer documentation

**Comment by cleveranu** [comment]
@Nishannaik please refer the documentation and make a pr again

**Comment by Nishannaik** [comment]
hey Ssitvit/Code-Canvas @Anukanksha Priya thanks for giving me
opportunity, i m sorry as I wasnt able to complete task due to my college
exams and later that physical 9 hour internship so can you please assign
task toanother?

**Comment by cleveranu** [comment]
ok

**Comment by Nishannaik** [comment]
Thanks!!!!

**Comment by Nishannaik** [comment]
Closed #397

**Pull request closed without merging**
