### PR TITLE
Unit Converter

### LINKED ISSUE #338: Unit_Converter
### Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Unit Converter** project under GSSoC'23.😁We all use this most used mobile application. I have made it with the use of HTML,CSS & JS.

**Expected behavior**

### Description
I have made a very basic Unit Converter where it just changes **foot to inch** & Vice-versa. Anyone can input integer or decimal. & there is also a up🔼 & down 🔽arrow. 

**Screenshots (optional)**

https://github.com/apu52/Unit-converter/assets/114172928/0b4d16dc-fbf8-4e7a-a63e-04bdb624aa18

**Additional context (optional )**

Please **Assign** me the issue🙏UNDER **gssoc'23**

### PR DESCRIPTION
**Pull request by apu52**
## Related Issue

Closes #338 

### Hello Sir/'Ma'am ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Unit Converter** project under GSSoC'23.😁We all use this most used mobile application. I have made it with the use of HTML,CSS & JS.

**Expected behavior**

### Description
I have made a very basic Unit Converter where it just changes **kilometer to meter to centimeter** & Vice-versa. Anyone can input integer or decimal. 

## Screenshots

Unit Converter

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by apu52** [comment]
@Shreyaar12 @cleveranu @Dharmesh177 @artimanputra please take a review of my PR & please merge it under GSSOC'23.

**Comment by Shreyaar12** [comment]
Please resolve merge conflicts

**Comment by apu52** [comment]
@Shreyaar12 @cleveranu I have resolved the conflicts. Please take a look & please merge the PR under SSOC

**Comment by cleveranu** [comment]
You can add more functionality and even more units for conversion.Try implementing !

**Comment by apu52** [comment]
@Shreyaar12 @cleveranu I have added a new unit converter project with more functionalities

**Comment by apu52** [comment]
Please take a look & after reviewing , Please merge it under GSSOC

**Pull request merged**
