### PR TITLE
Branch1: Fixed issue #381

### LINKED ISSUE #381: New pig game
2player Game created using using html,css,javascript.
i an gssoc23 contributor please assign this issue to me @Shreyaar12 @artimanputra @Dharmesh177

### PR DESCRIPTION
**Pull request by ePSA-eJya**
## Related Issue

Closes #381

## Screenshots

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

please merge the pr

### CODE REVIEW

**Comment by ePSA-eJya** [comment]
@Dharmesh177 pleasr merge the pr.

**Comment by Dharmesh177** [comment]
add video recording and screenshot in PR not showing on deploy link so

**Comment by ePSA-eJya** [comment]
> add video recording and screenshot in PR not showing on deploy link so


https://github.com/ssitvit/Code-Canvas/assets/120899038/19c1a10a-72cf-432d-ac5c-54354db60994

image
@Dharmesh177 
please review and merge

**Comment by ePSA-eJya** [comment]
please merge the pr @Dharmesh177 @artimanputra @Shreyaar12

**Comment by ePSA-eJya** [comment]
please add al level label @Dharmesh177

**Comment by killer2O** [comment]
@Dharmesh177 This project has already been added to https://github.com/kunjgit/GameZone/issues/1696

**Comment by ePSA-eJya** [comment]
> @Dharmesh177 This project has already been added to [kunjgit/GameZone#1696](https://github.com/kunjgit/GameZone/issues/1696)

No it's just an issue ....and the game was never merged....as  a pr was never created

**Comment by killer2O** [comment]
ok

**Comment by killer2O** [comment]
what kind of stupid game is this @Dharmesh177. at least check what the game is

**Comment by Dharmesh177** [comment]
PR was already merged as @ePSA-eJya already created many issues and PR of same game. 
@killer2O Please maintain decorum of open source community and gssoc'23 else you need face concivences.

**Comment by ePSA-eJya** [comment]
> PR was already merged as @ePSA-eJya already created many issues and PR of same game. @killer2O Please maintain decorum of open source community and gssoc'23 else you need face concivences.

Thanks a lot @Dharmesh177

**Pull request merged**
