### PR TITLE
Candy Crush Game added

### PR DESCRIPTION
**Pull request by singh-anushka**
Fixes [#161](https://github.com/ssitvit/Code-Canvas/issues/161)
<hr>
candy_crush

<br>
<hr>
<br>

## Rules of the game:

- The game will start with a 9x9 candy board.
- Use your mouse and interchange the places of the candies.
- As you form a line(either horizontal or vertical) of at least 3 candies you score at least 30 points.

<br>
<hr>
<br>

## Working video of the website:

https://github.com/ssitvit/Code-Canvas/assets/93376863/1d8df3e3-8824-49a5-bc8e-8ed90baa67d0

### CODE REVIEW

**Comment by Shreyaar12** [comment]
Kindly attach a working video as well

**Comment by singh-anushka** [comment]
@Shreyaar12 added the working video; should I do the same for all my PRs?

**Comment by Shreyaar12** [comment]
Please mention the rules for the game as well 

Video depends on what you're pushing we'll let you know if any other prs need it

**Comment by singh-anushka** [comment]
> Please mention the rules for the game as well
> 
> Video depends on what you're pushing we'll let you know if any other prs need it

I added the the rules for the game.

**Comment by singh-anushka** [comment]
Please merge this with the main code.
@artimanputra @Dharmesh177 @Shreyaar12 @cleveranu

**Comment by gurjeetsinghvirdee** [comment]
Hey @Dharmesh177 @artimanputra 
Mark this PR as invalid this project copied from here 


https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Candy_Crush

**Comment by singh-anushka** [comment]
> Hey @Dharmesh177 @artimanputra Mark this PR as invalid this project copied from here
> 
> https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Candy_Crush

How can you say that, this was added yesterday, while the very last commit of my PR was 5 days ago. So I would say they copied my rather than me.

**Comment by gurjeetsinghvirdee** [comment]
https://github.com/kunjgit/GameZone/pull/447

what to say now adding same project on different repos? @singh-anushka

**Comment by singh-anushka** [comment]
> [kunjgit/GameZone#447](https://github.com/kunjgit/GameZone/pull/447)
> 
> what to say now adding same project on different repos? @singh-anushka

Isn't that allowed?

**Comment by gurjeetsinghvirdee** [comment]
adding same project on 2-3 projects can lead to ban you on server & blacklist on the leaderboard

**Comment by singh-anushka** [comment]
> are you closing this PR

Yes I am

**Pull request closed without merging**
