### PR TITLE
Added New Project To-Do List

### PR DESCRIPTION
**Pull request by rayarka26**
issue Number #72
#gssoc23

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (41)

**Comment by rayarka26** [comment]
screenshot added please check

**Comment by rayarka26** [comment]
Screenshot (42)

**Comment by rayarka26** [comment]
please check @artimanputra

**Comment by artimanputra** [comment]
> please check @artimanputra

Make sure you add yourself as a contributor.

**Comment by rayarka26** [comment]
Where to add myself as a contributor ?
and do add gssoc23 labels
@artimanputra

**Pull request merged**
