### PR TITLE
Fix:README.md #344

### LINKED ISSUE #344: fix:Read me
I would like to fix the read me, as the contributors are not displaying in the read me file, and the project admin LinkedIn is not aligned properly.
Here  is the screenshot:
g2

### PR DESCRIPTION
**Pull request by iqrafirdose**
Added Linkedin, and GitHub icons, and added code of conduct, contributors .md , license file in read me. and fixed some typos. #344

## Related Issue

Closes #344

## Description

Added Linkedin, and GitHub icons, and added code of conduct, contributors .md, license file in Read me. and fixed some typos. 

## Screenshots

g6<br>
g7

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Dharmesh177** [comment]
Great need some changes Add mentor section 
Mentor 1 - Dharmesh Vala
Mentor 2 - Arti Manputra

**Comment by Dharmesh177** [comment]
Dharmesh Linkedin - https://www.linkedin.com/in/dharmesh-vala-252724204/
Arti Linkedin - https://www.linkedin.com/in/arti-manputra/
Dharmesh Github - https://github.com/Dharmesh177
Arti Github - https://github.com/artimanputra/
for photo connect in linkedin

**Comment by iqrafirdose** [comment]
> Dharmesh Linkedin - https://www.linkedin.com/in/dharmesh-vala-252724204/ Arti Linkedin - https://www.linkedin.com/in/arti-manputra/ Dharmesh Github - https://github.com/Dharmesh177 Arti Github - https://github.com/artimanputra/ for photo connect in linkedin



> Great need some changes Add mentor section Mentor 1 - Dharmesh Vala Mentor 2 - Arti Manputra

Ok, Can you please send the photos and I sent the connection requests on Linkedin.

**Comment by iqrafirdose** [comment]
I just saw the image of the project admin and project maintainer redirecting to their GitHub. So, I also redirected project mentors' images to their Github. Can you please make this PR under GSSoc as I am contributing to gssoc?

**Comment by iqrafirdose** [comment]
> I just saw the image of the project admin and project maintainer redirecting to their GitHub. So, I also redirected project mentors' images to their Github. Can you please make this PR under GSSoc as I am contributing to gssoc?

Can you please check out @Dharmesh177 @artimanputra

**Pull request merged**
