### PR TITLE
Travel website[GSSOC'23]

### LINKED ISSUE #502: Travel_Website[GSSOC'23]
### Project title
**Travel_Website**

### Project Description
Hello Coders👨‍💻 ,I am Arpan Chowdhury, a aspiring Web developer.🤖 Here is the project of the front-end Web Development. This repo contains my project on Travel Website ✈️ using HTML,CSS . It contains the landing page of a travel tour company website👨🏻‍💻.We oftenly search for many travelling places here & there , So Here is it🚤

## Screenshots
image
image

Please assign me the issue

### PR DESCRIPTION
**Pull request by apu52**
## Related Issue

Closes #502 

###  Travel Website
Issue No. #502

This repo contains my project on Travel Website ✈️ using HTML,CSS . It contains the landing page of a travel tour company website👨🏻‍💻.We oftenly search for many travelling places here & there , So Here is it🚤.

## Screenshots
Travel Website

## Video

https://github.com/ssitvit/Code-Canvas/assets/114172928/d0c6bdb2-a470-4f7d-9f7b-9d535d3d50ac

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by apu52** [comment]
@Shreyaar12 @cleveranu @Dharmesh177 @artimanputra please take a review of my PR & please merge it under GSSOC'23.

**Comment by apu52** [comment]
@cleveranu I have already resolved the conflicts.  please kindly look at those. & after reviewing please merge it under Gssoc'23.

**Comment by cleveranu** [comment]
Plz look again

**Comment by apu52** [comment]
@cleveranu I have again resolved the conflicts. please kindly look at those. & after reviewing please merge it under Gssoc'23.

**Pull request merged**
