### PR TITLE
Added category filter option for projects. [ Fixes : #44 ]

### PR DESCRIPTION
**Pull request by ritik48**
Added search input and dropdown in index.html and required css in the style.css file.
And created filter_search.js file to filter out the project on the basis of user search.

- Implementation preview:

https://github.com/ssitvit/Code-Canvas/assets/84488726/09ee35fe-c726-455b-9b4a-854d324ba237

### CODE REVIEW

**Comment by cleveranu** [comment]
Can you add a bit more CSS (border-radius, reduce width of search bar } and change color to white not green and also give a little space between seach bar and choosing options

**Comment by ritik48** [comment]
@cleveranu yes sure, will make another pull request by changing the css

**Comment by ritik48** [comment]
@cleveranu please review the changes

**Comment by cleveranu** [comment]
Good job!!

**Comment by ritik48** [comment]
@cleveranu thanks a lot.

**Comment by ritik48** [comment]
@cleveranu please assign level tag to this pr.

**Pull request merged**
