### PR TITLE
reaction test game and favicon is added

### PR DESCRIPTION
**Pull request by Sushilverma002**
close issues #175 and #176 .

https://github.com/ssitvit/Code-Canvas/assets/114687502/ca557bd9-f8af-44bf-b037-b602b08e8d2f

### CODE REVIEW

**Comment by Sushilverma002** [comment]
please merge it. its more than 20 days

**Comment by Dharmesh177** [comment]
Add page or box showiing rule to play game and how it beneficial to anyone in your project 
complete asap and let me know in discord

**Comment by Sushilverma002** [comment]
image
updated

**Comment by Sushilverma002** [comment]
it is in desktop mode already

**Comment by Sushilverma002** [comment]
and it will work on both desktop as well as in phone

**Pull request closed without merging**
