### PR TITLE
Updated the README.md file

### PR DESCRIPTION
**Pull request by Anikinee**
Solved issue #75 

1. Added "Technology Stack" section.
2. Added " Repo Status" section.
3. Added "License" section.
4. Added "back to top" button.
5. Changed the location of "Team" section.
6. Modified "Contributors" section.
7. Added images of the website.
8. Modified the contributing steps.

Screenshot (401)
Screenshot (402)

Please check it out and let me know if any changes are to be made. @artimanputra

### CODE REVIEW

**Comment by Dharmesh177** [comment]
mention which issue you're addrresing

**Comment by Dharmesh177** [comment]
Resolve confilict

**Comment by Anikinee** [comment]
> Resolve confilict

I have resolved the conflict.

**Comment by Anikinee** [comment]
> mention which issue you're addrresing

I have already mentioned the issue along with the changes I made. Still, letting you know once more it's issue #75 .

**Pull request merged**
