### PR TITLE
Created a Rock Paper Scissors Game

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
Addresses #183 
Made a Rock Paper Scissors Game
A single player game 
here's some snaps

image

image

image

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@artimanputra Check out this PR

**Review by PoulavBhowmick03 — COMMENTED** [review]
Added the game card in index.html file

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 I have added it. Pls check now

**Comment by artimanputra** [comment]
> @Dharmesh177 I have added it. Pls check now

Hey, Please share a screen recording of your project

**Comment by PoulavBhowmick03** [comment]
Here is the game itself
I've added the link in the README.md
@artimanputra

**Comment by artimanputra** [comment]
> 

Ok Great I will merge it

**Pull request merged**
