### PR TITLE
[GSSoC'23] Morse Code Convertor Completed

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Morse Code Convertor
Technology used - HTML, CSS and JS
Issue Fixes - #234 

This project can convert entered text into morse code instantly.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @artimanputra @Shreyaar12 Please review my pull request and merge it into the main branch for a successful contribution under GSSoC'23

**Comment by Avdhesh-Varshney** [comment]
@cleveranu @Dharmesh177 @artimanputra @Shreyaar12 please review my pull request and merge it into the main branch for a successful contribution under GSSoC'23

**Review by Shreyaar12 — CHANGES_REQUESTED** [review]
Kindly resolve merge conflicts then push

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 maam i am not able to see the merge conflicts. please explain it so that i can resolve and commit the changes
please review

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 @cleveranu @artimanputra @Dharmesh177  please review this pull request and requested to merge this pr for a successful contribution under GSSoC'23 program

**Comment by Dharmesh177** [comment]
Follow contributing.md guide for successful PR merge

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 @Dharmesh177 @cleveranu @artimanputra please again review this pull request.
I have done with the all changes and requested to merge it into the main branch for a valuable contribution under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
@Dharmesh177 @artimanputra @Shreyaar12 @cleveranu 
Sirs, I have created this pr 2 weeks ago, please review this pr and requested to merge this pr for a successful contribution under GSSoC'23 program

Please Sirs !

**Comment by Dharmesh177** [comment]
spam as already submmited this to other project as well

**Pull request closed without merging**
