### PR TITLE
a reaction tester game and favicon se added

### PR DESCRIPTION
**Pull request by Sushilverma002**
## Related Issue #307 

Closes #issue_number 
#175 #176 

## Screenshots

image

## Checklist 

- [X ] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [X ] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Sushilverma002** [comment]
sir i have created multiple time because every time i updated it show conflict and i have to make new PR you can closed after merge. i have been waited literally more than 3week  to merge and in last you just closed that's not fair sir

**Comment by Dharmesh177** [comment]
Okay I'm giving more one chance to u open only that pr which is last and up to date

**Comment by Sushilverma002** [comment]
okay!

**Comment by Sushilverma002** [comment]
#408 here it is the final PR and checked form mine side in last your decision is final one . now it is up to you @Dharmesh177 .

**Pull request closed without merging**
