### PR TITLE
Favicon and reaction tester GAME both here.

### PR DESCRIPTION
**Pull request by Sushilverma002**
issues is solved favicon is designed and added in index.html
issue #176 and #175

### CODE REVIEW

**Comment by Sushilverma002** [comment]
please review it and merge it

**Comment by Sushilverma002** [comment]
@Dharmesh177 please merge it

**Comment by Sushilverma002** [comment]
@Dharmesh177 sir please review this PR and merge it.

**Comment by Sushilverma002** [comment]
@Dharmesh177 @artimanputra please review and merge.

**Comment by Dharmesh177** [comment]
solve conflict first

**Pull request closed without merging**
