### PR TITLE
Branch2: fixed #380

### LINKED ISSUE #380: Amazon clone
Amazon clone using html,css,javascript.
i an gssoc23 contributor please assign this issue to me @Shreyaar12 @artimanputra @Dharmesh177

### PR DESCRIPTION
**Pull request by ePSA-eJya**
## Related Issue

Closes #380 

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

@Dharmesh177 please merge my pr.

### CODE REVIEW

**Comment by Dharmesh177** [comment]
not able to find your project in home page of deployed link kindly follow contributing.md guide for successful pr merge

**Comment by ePSA-eJya** [comment]
image
  
image
 here its available in the deploy preview

@Dharmesh177 please review and merge

**Comment by ePSA-eJya** [comment]
please merge the pr @Dharmesh177 @artimanputra @Shreyaar12

**Comment by Dharmesh177** [comment]
not responsive make it responsive

**Pull request closed without merging**
