### PR TITLE
Added Dragon_World_Game(GSSOC '23) Issue: #244)

### PR DESCRIPTION
**Pull request by sujanrupu**
Added Dragon World Game under GSSOC '23, issue: #244
## Screenshot:
dragon_world

## Demo video:

https://github.com/ssitvit/Code-Canvas/assets/103595490/36c19312-7e0c-44d9-b283-5701fe85241a

### CODE REVIEW

**Comment by sujanrupu** [comment]
@Dharmesh177 Please review the PR.

**Comment by sujanrupu** [comment]
@Shreyaar12   @Dharmesh177 please review the PR and merge.

**Comment by Dharmesh177** [comment]
Add rule to play game

**Comment by sujanrupu** [comment]
> Add rule to play game
@Dharmesh177 at the game readme file 'how to play the game' is mentioned .

**Comment by Dharmesh177** [comment]
Add that in game

**Comment by cleveranu** [comment]
Please resove merge conflict

**Comment by sujanrupu** [comment]
@cleveranu I have resolved the conflict, please review my PR

**Comment by cleveranu** [comment]
please add instructions how to play the game in the game

**Pull request closed without merging**
