### PR TITLE
Fixed The Bingo Card & Added "To Top" Button

### LINKED ISSUE #432: Adding "To Top" Scroll Button and Fixing the Top
I would like to add an arrow button to the right that, on clicking, would take the user to the top of the page.

I would also like to fix this issue that appears on the top:(Seems to be a project card)
image

It would be great to contribute to this open source project under GSSoC '23!

### PR DESCRIPTION
**Pull request by 5h0ov**
## Related Issue

Closes #432 

## Description

- Successfully fixed the Bingo Card Game that appeared on the top and fixed the projects appearing properly in the project section!

- Added a "To Top" button to the bottom right that appears when the user scrolls to a certain part of the website and clicking it takes the user back to top.
## Screenshots
Fixed Top of Webpage:
image

Scroll To Top:
scroll

## Checklist 

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by 5h0ov** [comment]
@Dharmesh177  take a look sir! Its fixed 😄

**Comment by Dharmesh177** [comment]
Scroll up button not working

**Comment by 5h0ov** [comment]
but sir look its working in phone as well

@https://github.com/ssitvit/Code-Canvas/assets/83227649/fabfdf3a-f9f8-42ef-ad37-d98b15c93952

**Comment by 5h0ov** [comment]
i looked in desktop again and its working 😅

**Comment by 5h0ov** [comment]
maybe now try? i reduced the pixels it takes to show the button

**Comment by 5h0ov** [comment]
@Dharmesh177  sir could u check it again?

**Comment by 5h0ov** [comment]
@Shreyaar12  maam can you take a look at the PR and review it please?

**Pull request merged**
