### PR TITLE
Solve the issue number #544

### LINKED ISSUE #544: Add Hover Effect to the Screenshotted positions & Make Navbar stick to top
I would like to add a hover effect to these parts:

image

image

I would also like to change the font color of the light to dark switch to make it be visible clearly!

image

I would also like to make the navbar stick to the top

It would be great to contribute to this repo under GSSoC '23

### PR DESCRIPTION
**Pull request by simrraann8**
## Related Issue

Closes #544 

## Description

Changes the font color of the light to dark switch to make it be visible clearly and also added font family and font weight

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by 5h0ov** [comment]
hey you opened a PR on my issue which even I am not assigned! @cleveranu  please kindly look into this

**Comment by simrraann8** [comment]
> hey you opened a PR on my issue which even I am not assigned! @cleveranu please kindly look into this
But I think we can work on any of the opened issue

**Comment by 5h0ov** [comment]
> > But I think we can work on any of the opened issue

no no you can only create a PR on an issue that has been assigned to you!

**Comment by simrraann8** [comment]
> > > But I think we can work on any of the opened issue
> 
> no no you can only create a PR on an issue that has been **assigned** to **you**!

Okay Thanks

**Pull request closed without merging**
