### PR TITLE
[GSSoC'23] Bingo Game Completed

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Bingo Game
Technology Used - HTML, CSS and JS

Issue fixed - #295 

- This is a multiplayer game
- This game has background music with sound controls like mute, unmute and volume slider.
- Providing a responsive interface for mobile devices

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@cleveranu @Dharmesh177 @artimanputra please review this pull request and requested to merge this pr into the main branch for a successful contribution under GSSoC'23

**Review by Shreyaar12 — CHANGES_REQUESTED** [review]
It gives an alert about game draw and then shows player 1 wins, please fix

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 @cleveranu @Dharmesh177 @artimanputra please review my pull request again and requested to merge it into the main branch of this repository for a successful contribution under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
@Shreyaar12 please review my pull request and requested to merge it into the main branch for a successful contribution under GSSoC'23

**Comment by Avdhesh-Varshney** [comment]
> It gives an alert about game draw and then shows player 1 wins, please fix

@Shreyaar12 @Dharmesh177 @artimanputra I have done with the changes and removed the bug. Now, please review this pull request and requested to merge it into the main branch of this repository for a successful contribution under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
please review this pull request @Shreyaar12 and merge it into the main branch of this repository for a valuable contribution under GSSoC'23 program

**Pull request merged**
