### PR TITLE
Added Candy Crush Game

### LINKED ISSUE #270: Candy Crush Game
Create a Candy Crush Game using HTML, CSS and Javascript
User will be able to drag the elements to match 3 of them and get points

image

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
Close #270 
Made a candy crush game using html css and javascript
Here's it's functioning and link

https://poulavbhowmick03.github.io/CandyCrush/

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 Check out

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 @Shreyaar12  Please have a look at it

**Comment by PoulavBhowmick03** [comment]
Hey @Dharmesh177 please merge this pr

**Comment by PoulavBhowmick03** [comment]
@Dharmesh177 please merge the PR

**Review by Shreyaar12 — CHANGES_REQUESTED** [review]
Add rules in the game page

**Comment by PoulavBhowmick03** [comment]
> Add rules in the game page

You mean in the readme file?

**Comment by Dharmesh177** [comment]
@PoulavBhowmick03 there is some minor bug like when i start game defaut score is 7 there and if we move unmatch pair then paired swapped but it shouldn't

**Comment by Dharmesh177** [comment]
and you still not added rule in your game 

suggestion : put one page of rule and start btn as well as you can add some music while pair match and animation etc

**Review by PoulavBhowmick03 — COMMENTED** [review]
Added Rules Page

**Pull request merged**
