### PR TITLE
[GSSoC'23]: Added Hangman Game

### LINKED ISSUE #404: GSSoC'23 : Add Hangman Game
# Hangman Game
I would like to contribute to the Hangman project, which is a word-guessing game implemented using HTML, CSS, and JavaScript. The game allows players to select word categories, make guesses, and complete the word within a certain number of attempts. 

# Expected behavior
The expected behavior is that the game should function correctly, allowing players to select word categories, make letter guesses, and determine whether they win or lose based on their progress and the completion of the hangman figure. The game should provide accurate feedback on the result and allow players to start a new game when desired.

### PR DESCRIPTION
**Pull request by palakag29**
## Issue
- #404

Closes #404 

## Description

Hangman project, which is a word-guessing game implemented using HTML, CSS, and JavaScript. The game allows players to select word categories, make guesses, and complete the word within a certain number of attempts.

## Screenshots

https://github.com/ssitvit/Code-Canvas/assets/112793075/e1a1add9-eeca-42c8-94a8-a752f2f6bfa6

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by ePSA-eJya** [comment]
this issue has been assigned to me @Dharmesh177 #386

**Comment by Dharmesh177** [comment]
Already assigned to someone

**Comment by palakag29** [comment]
it is assigned to me also https://github.com/ssitvit/Code-Canvas/issues/404

**Comment by palakag29** [comment]
@Dharmesh177  please check

**Comment by ePSA-eJya** [comment]
> @Dharmesh177 please check

it was assigned to me before it was to you @palakag29

**Pull request closed without merging**
