### PR TITLE
Added Netflix-Clone

### LINKED ISSUE #541: [New Project]: Netflix Clone
Hello @cleveranu ,
I have a project for bettre User Experience while surfing the website and it is `Netflix Clone` which I have made using HTML, CSS, JavaScript & RapidAPI.

- It is Fully Responsive 🥇 

### Video of the Project :
[Screencast from 04-08-23 10:39:06 PM IST.webm](https://github.com/ssitvit/Code-Canvas/assets/121503426/9d7e0be0-1400-4c24-91d7-5a741e83d074)

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Closes #541 

## Description
Hello @cleveranu ,
Added a `Netflix Clone (replica)` done.
Kindly merge this waiting for your review. 👍🏻 

## Video
[Screencast from 04-08-23 11:28:28 PM IST.webm](https://github.com/ssitvit/Code-Canvas/assets/121503426/5271097c-d481-42e5-8c08-a7263d4b023a)

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

```
Good label will really appreciated
```

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
@cleveranu this need to be reviewed.

**Comment by cleveranu** [comment]
Your bg image is not loading do chck out

**Comment by SyedImtiyaz-1** [comment]
> Your bg image is not loading do chck out

Sure

**Comment by SyedImtiyaz-1** [comment]
@cleveranu Issue Fixed regarding the Background Image.
You can merge this now.

image

**Pull request merged**
