### PR TITLE
Added space themed website

### LINKED ISSUE #507: Add space website.
I would like to make a space website using HTML and CSS.

### PR DESCRIPTION
**Pull request by PVBharadwaj**
## Related Issue
#507 

Closes #507 

## Description

I have added a new front-end space website. It is made using HTML, and CSS.

## Checklist 

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by PVBharadwaj** [comment]
@cleveranu  please review this pr under gssoc'23

**Comment by cleveranu** [comment]
Good work!!

**Comment by PVBharadwaj** [comment]
@cleveranu The score of this PR didn't get added to my leaderboard. Please check the issue once.

**Comment by cleveranu** [comment]
check now

**Comment by PVBharadwaj** [comment]
Done. Thank you

**Pull request merged**
