### PR TITLE
Re-designing of Home Page #526

### LINKED ISSUE #526: Re-designing of Home Page
The home page of the website does not look appealing to a visitor, it gives a history vibe, I want to work on the UI part and I want to re-design the home page to make it more attractive and engaging. I want to work on this issue under GSSOC23, kindly assign this to me.

### PR DESCRIPTION
**Pull request by Manishak798**
## Related Issue

Closes #526 

## Description
I have entirely re-designed the home page and added new fonts and colors to the website that will make it look more appealing.

## Screenshots
Before
image
After
image
image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Manishak798** [comment]
hey @cleveranu please check my PR.

**Comment by cleveranu** [comment]
even the animation is not present in this page

**Comment by Manishak798** [comment]
Hey @cleveranu as per your views on my previous work, I changed the UI accordingly added the animation, and makes it look appealing. Please check my PR.
SCREENSHOT
image

**Review by Shreyaar12 — CHANGES_REQUESTED** [review]
fix the button config and not many changes with respect to theme happening in the light/dark mode

**Comment by Manishak798** [comment]
> fix the button config and not many changes with respect to theme happening in the light/dark mode

Can you elaborate this a bit more

**Comment by Manishak798** [comment]
Hey @Shreyaar12 I have reviewed your request as my work included redesigning the home page I did, Now in dark mode the title is not visible that is the new issue, and even if we refresh the page the enabled dark theme converts to light mode does not look appealing, Please accept my PR for designing the home page and I will raise two new issues and work upon the other this as a contributor under GSSOC my PR matters and I hope you understand that.
Thank you

**Comment by Manishak798** [comment]
Hey @Shreyaar12 Please review my request.

**Comment by Manishak798** [comment]
Hey @cleveranu please review my PR.

**Comment by Manishak798** [comment]
Hey @Shreyaar12 please view my PR.

**Comment by Manishak798** [comment]
Hey @Shreyaar12 Kindly check my PR.

**Comment by Manishak798** [comment]
@Shreyaar12 Kindly review my PR as tomorrow is the last day of GSSOC.

**Comment by Manishak798** [comment]
Hey @cleveranu @Shreyaar12 kindly check my PR.

**Comment by Manishak798** [comment]
Hey @cleveranu kindly check my PR.

**Comment by Manishak798** [comment]
Hey @Shreyaar12 kindly review my PR as it's the last day of GSSOC.

**Comment by Manishak798** [comment]
Hey, @cleveranu, today is the last day of GSSOC23. I urge you to review my PR as I delicately worked on it and submit it to you on time. It's already been a week now and I did not even hear back from you. I request you to please review my PR.

**Comment by Manishak798** [comment]
Hey @Shreyaar12 I request you to review my PR as today is the last day of GSSOC23.

**Comment by Manishak798** [comment]
Hey @Shreyaar12 Kindly check my PR.

**Comment by Manishak798** [comment]
Hey, @cleveranu and @Shreyaar12 Kindly, check my PR.

**Comment by Manishak798** [comment]
Hey @cleveranu kindly view my PR.

**Pull request closed without merging**
